micronaut:
  application:
    name: kafka-word-filtering
  http:
    services:
      filtering-service:
        url: 'https://api.filtering-service.localhost:8080'

kafka:
  streams:
    default:
#     application.id: "kafka-word-count"
     processing.guarantee: "exactly_once"
     auto.offset.reset: "earliest"
     commit.interval.ms: 500
     num.stream.threads: 1
#     default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#     default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde