micronaut:
  application:
    name: kafka-word-filtering
  http:
    services:
      filtering-service:
        url: 'https://api.filtering-service.localhost:8080'

kafka:
  streams:
    default:
     processing.guarantee: "exactly_once"
     auto.offset.reset: "earliest"
     commit.interval.ms: 500
     num.stream.threads: 1